name: React.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd App/Presentation
    - run: npm ci
      working-directory: ./App/Presentation
    - name: Run tests
      run: node --trace-deprecation ./node_modules/.bin/jest
      working-directory: ./App/Presentation
      timeout-minutes: 2
    - run: npm run build --if-present
      working-directory: ./App/Presentation